---
- name: "create directory"
  shell: |
    cd /home/ubuntu/
    rm -rf uda_app
    mkdir uda_app

- name: "copy backend binaries"
  become: yes
  copy:
    src: ../../artifact.tar.gz
    dest: /home/ubuntu/uda_app
    

- name: "extract backend folder"
  shell: |
    cd /home/ubuntu/uda_app
    tar -xf artifact.tar.gz
    rm -rf artifact.tar.gz


- name: "delete anything that might already be running"
  become: true
  command: pm2 delete all
  ignore_errors: true

# - name: "start server"
#   become: true
#   command: pm2 start -f ./main.js
#   args:
#     chdir: /home/ubuntu/uda_app/dist

- name: "start server"
  become: true
  shell : |
    cd /home/ubuntu/uda_app
    pm2 start npm -- start
