---
- name: "install dependencies."
  become: true
  apt:
    name: "tar"
    state: latest
    update_cache: yes

- name: "copy backend binaries"
  become: yes
  copy:
    src:  /root/project/artifact.tar.gz
    dest: /home/ubuntu/
    

- name: "Untar backend folder"
  become: true
  shell: |
    cd /home/ubuntu/
    tar -xzvf artifact.tar.gz

- name: Install Node modules
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm i
- name: Building backend
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm run build
- name: Start pm2 service
  become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start